### ISSUE TITLE
Not concave Polygon

### ISSUE THREAD

**Issue by Menqsey** [orbisgis/jdelaunay#16]
Sorry when i process triangulation I only get convex polygon. Whenever the new Edge makes polygon concave that edge is no counted. Could you tell me what the problem is

**Comment by ebocher** [comment]
Please note that "This project is no longer being actively developed or maintained."

**Comment by nicolas-f** [comment]
Hi.

This is a delaunay triangulation not a tesselation. The appropriate library is https://github.com/orbisgis/poly2tri.java

**Comment by Menqsey** [comment]
Thanks very much. 
If you could send me an example  for  polygon (concave), and getting triangles with poly2tri, I would appreciate that.

**Comment by nicolas-f** [comment]
You have the unit test here:
https://github.com/orbisgis/poly2tri.java/blob/master/poly2tri-core/src/test/java/org/poly2tri/TestConstrainedDelaunay.java#L164
It uses points defined in https://github.com/orbisgis/poly2tri.java/blob/master/poly2tri-core/src/test/resources/org/poly2tri/poly2.dat
